### PR TITLE
all changes needed for fixing condos in PDE

### PR DESCRIPTION
**Pull request by ajrothwell**

### CODE REVIEW

**Comment by stevetotheizz0** [comment]
-It appears that using the address input form doesn't work with condos. 

-I noticed with an owner search, that subsequent geocode searches show that total before retrieving the condo result and showing 1 result. (The owner total will keep popping up briefly if you click other condo buildings in a row.)

-An error "Cannot read property '_featureId' of undefined" shows up before the page searches again for the condo on geocoded searches. 

-Owner search adds first address to url instead of owner term

**Comment by stevetotheizz0** [comment]
Which issues and features does this PR fix/add?

**Comment by ajrothwell** [comment]
@stevetotheizz0 - 
https://github.com/CityOfPhiladelphia/property-data-explorer/issues/333

**Comment by stevetotheizz0** [comment]
- On address search, button doesnt appear to load the units. 

-Searching either by address, or using the back/forward nav, or pasting the url briefly/awkwardly loads the intro page before returning results.

**Pull request merged**
